spring.application.name=resumer
spring.ai.google.genai.api-key=AIzaSyAnUwlbQ51H45L8hxxt6q9xDydZjbBvxr0
# This tells Spring Boot to use the Gemini model
spring.ai.google.genai.chat.options.model=gemini-1.5-flash-001