spring.application.name=resumer
spring.ai.google.genai.api-key=AIzaSyBhoP4buV5Z4vxCw7tD501to6vdxXkCFSY
# This tells Spring Boot to use the Gemini model
spring.ai.google.genai.chat.options.model=gemini-1.5-flash